[project]
name = "169-tutti"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "gaspard>=0.0.1",
    "loguru>=0.7.3",
    "pandas>=2.3.3",
]
